### ISSUE TITLE
Create DB if it doesn't exist

### ISSUE THREAD

**Issue by hyavari** [ugoviti/izdock-izpbx#17]
I think it would be good to add a checking script in entrypoint-hooks.sh and checks if "asterisk" DB doesn't exist, create it before installation. It removes the dependency/ limitation of one DB creation in DB docker.

Something like this:

mysql -h ${MYSQL_SERVER} -P ${APP_PORT_MYSQL} -u root --password=${MYSQL_ROOT_PASSWORD} -B -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}"

**Comment by ugoviti** [comment]
Hi,

thank you for your feedback.

Can you give me more details?

When starting izPBX for the first time, is FreePBX install script that create the missing 'asterisk' and 'asteriskcdrdb' database, what is the problem that you are experiencing?

Thank you

**Comment by hyavari** [comment]
I am not sure about 'asterisk' DB. I checked again entrypoint* scripts but didn't find that point. Please let me know where you are creating 'asterisk'.
I as I know, we have to run a separate container for DB and create 'asterisk'.

But for running the second FPBX instance, you have to do it manually like 'asterisk2'. So, I think it would be good to handle it and create 'asterisk2' if it doesn't exist.

**Comment by ugoviti** [comment]
Hi, 

the database will be created only if new installation is tirggered:

function `cfgService_freepbx_install` `if [ ! -e ${APP_DATA}/.initialized ]`

the database is created by `./install -n --skip-install --no-ansi --dbhost=${MYSQL_SERVER} --dbuser=${MYSQL_USER} --dbpass=${MYSQL_PASSWORD} ${FPBX_OPTS}` command.

anyway I just pushed into `dev` branch the commit 0f75c9a0a86085d58702535a97c43b3047647355 to allow the use of custom `asteriskcdrdb` and the manual creation of db, before running `./install` script

can you test and make me report before promoting to stable release? 

CI is building right now, when pushed into docker hub, you can test with:

`docker pull izdock/izpbx-asterisk:dev-18`

Kind regards

**Comment by ugoviti** [comment]
closed by https://github.com/ugoviti/izdock-izpbx/commit/d324daad7727c87db6ab584e9439fe4390756ff0 and release 18.15.6

**Comment by danielkucera** [comment]
Hi, I'd like to avoid giving db root password. Can we do this only when `MYSQL_ROOT_PASSWORD` env var is defined?

**Comment by danielkucera** [comment]
Ah, it seems to be not an issue because after several retires it continues anyway:
```
ERROR 1045 (28000): Access denied for user 'root'@'10.88.0.133' (using password: NO)
--> WARNING: cannot connect to MySQL database 's.danman.eu'... waiting database to become ready... retrying in 10 seconds... try:[2/10]
ERROR 1045 (28000): Access denied for user 'root'@'10.88.0.133' (using password: NO)
--> WARNING: cannot connect to MySQL database 's.danman.eu'... waiting database to become ready... retrying in 10 seconds... try:[3/10]
ERROR 1045 (28000): Access denied for user 'root'@'10.88.0.133' (using password: NO)
--> WARNING: cannot connect to MySQL database 's.danman.eu'... waiting database to become ready... retrying in 10 seconds... try:[4/10]
ERROR 1045 (28000): Access denied for user 'root'@'10.88.0.133' (using password: NO)
--> WARNING: cannot connect to MySQL database 's.danman.eu'... waiting database to become ready... retrying in 10 seconds... try:[5/10]
ERROR 1045 (28000): Access denied for user 'root'@'10.88.0.133' (using password: NO)
--> WARNING: cannot connect to MySQL database 's.danman.eu'... waiting database to become ready... retrying in 10 seconds... try:[6/10]
ERROR 1045 (28000): Access denied for user 'root'@'10.88.0.133' (using password: NO)
--> WARNING: cannot connect to MySQL database 's.danman.eu'... waiting database to become ready... retrying in 10 seconds... try:[7/10]
ERROR 1045 (28000): Access denied for user 'root'@'10.88.0.133' (using password: NO)
--> WARNING: cannot connect to MySQL database 's.danman.eu'... waiting database to become ready... retrying in 10 seconds... try:[8/10]
ERROR 1045 (28000): Access denied for user 'root'@'10.88.0.133' (using password: NO)
--> WARNING: cannot connect to MySQL database 's.danman.eu'... waiting database to become ready... retrying in 10 seconds... try:[9/10]
ERROR 1045 (28000): Access denied for user 'root'@'10.88.0.133' (using password: NO)
--> WARNING: cannot connect to MySQL database 's.danman.eu'... waiting database to become ready... retrying in 10 seconds... try:[10/10]
--> installing FreePBX in '/data/var/www/html'
---> START install FreePBX @ Fri Jan 21 11:50:21 UTC 2022
++ mysql -h s.danman.eu -P 3306 -u root --password= -B -e 'CREATE USER IF NOT EXISTS '\''izpbx'\''@'\''%'\'' IDENTIFIED BY '\''.......'\'';'
ERROR 1045 (28000): Access denied for user 'root'@'10.88.0.133' (using password: NO)
++ mysql -h s.danman.eu -P 3306 -u root --password= -B -e 'CREATE DATABASE IF NOT EXISTS asterisk'
```

**Comment by ugoviti** [comment]
Hi, nice suggestion... yes I can manage that... Let's me working on.

Kind Regards

**Comment by ugoviti** [comment]
Hi,

relased https://github.com/ugoviti/izpbx/releases/tag/18.16.3

can you test if working as expected and report here problems?

Thank you.

Kind Regards

**Comment by danielkucera** [comment]
I haven't tried reinstall but deployed a new version and It works fine.
Thank you.
