### ISSUE TITLE
regenerating the containers looses custom Chan SIP/PJSIP ports

### ISSUE THREAD

**Issue by dariuscardren** [ugoviti/izdock-izpbx#2]
I've got PJsip on 5060 and chan SIP on 5160 in this instance, when I rebuild the container, it is swapping the ports to the default of chan sip on 5060 and PJ SIP on 5160 

I know chan sip port is defined here
/etc/asterisk/sip_general_additional.conf

and PJ SIP is here
/etc/asterisk/pjsip.transports.conf

I am not sure if this setting is regenerated from the freepbx DB or not it appears to not be.

**Comment by ugoviti** [comment]
Hi,

these ports are reconfigured by settings in the `.env` file (if you edit from FreePBX GUI, they will be overrided on every container start)

solution:

edit `.env` file:
```
APP_PORT_PJSIP=5160
APP_PORT_SIP=5060

and run:
```
docker-compose up -d
```

Kind Regards
