### ISSUE TITLE
Freepbx API 

### ISSUE THREAD

**Issue by ldcsirtest2012** [ugoviti/izdock-izpbx#20]
Hi  when i install pbx api  
Get url   192.168.11.106/admin/api/api/token
got error
{
error: {
type: "Exception",
message: "Module requested invalid",
file: "/data/var/www/html/admin/libraries/BMO/Ajax.class.php",
line: 44
}
}

**Comment by ugoviti** [comment]
Hi, 

I think this is a FreePBX problem, just tried to install the PBX API 15.0.3.15 and got the same error:

```
{"error":{"type":"Exception","message":"Module requested invalid","file":"\/data\/var\/www\/html\/admin\/libraries\/BMO\/Ajax.class.php","line":44}}
```

Can you first try to search or open an issue into https://issues.freepbx.org/ ?

Thank you

Kind regards

**Comment by ldcsirtest2012** [comment]
Thank you for your reply！
I found a possible reason。
/var/www/html/admin/api/.htaccess notwork  in docker
