### ISSUE TITLE
[feature] Change AMI port

### ISSUE THREAD

**Issue by ldcsirtest2012** [ugoviti/izdock-izpbx#21]
Dear developer!
I hope to add the function of modifying asterisk AMI port
thank you

**Comment by ugoviti** [comment]
Hi,

thank you for your report, should be fixed with release 18.15.15 (compiling right now, wait 1 hour) can you try and send a feedback?

Kind Regards

**Comment by ugoviti** [comment]
Fixed in 48c28bad984b8232b4208ea080a0de1230dc5ea2
