### ISSUE TITLE
Letsencrypt

### ISSUE THREAD

**Issue by ulug79** [ugoviti/izdock-izpbx#25]
Please add DNS challenge for certificate generation. Or add possibility to specify the folder with certificates

**Comment by ugoviti** [comment]
Hi,

thank you for the suggestions, but the Let's Encrypt certificates are managed by FreePBX `fwconsole` commmad that doesn't support DNS challenge. You can open a Feature Request into FreePBX bugtraking if you want.

Anyway I enhanced the self-signed and custom certificate management adding three new variables that you can use to customize your HTTPS settings.

Released as 18.15.20 (building now, let it finish the push into docker hub)

Let's me know if this solve your needs, so I can close this issue.

Kind Regards

**Comment by ulug79** [comment]
Hi,

My docker hosts use traefik load balancer. 
Traefik with dns challenge request certificate from letsencrypt. other container extract certificate if renewed and restart all needed containers.

Please add using of custom certificate. for example enviroment variables 
SSL_CERT_KEY=/appdata/certs/cert.key
SSL_CERT_NAME=/appdaya/certs/cert.crt

**Comment by ugoviti** [comment]
Yes, since 18.15.20 release you can use these variables:

  - `HTTPD_HTTPS_CERT_FILE`
  - `HTTPD_HTTPS_KEY_FILE`
  - `HTTPD_HTTPS_CHAIN_FILE`

Let me know if this works for you.

Thank you

**Comment by ulug79** [comment]
Thanks for your great work!
