### ISSUE TITLE
Configure Postfix with Gmail

### ISSUE THREAD

**Issue by faspina** [ugoviti/izdock-izpbx#6]
Very new to FreePBX

I would like to configure postfix to send via gmail relay. How to I set this up

**Comment by ugoviti** [comment]
Hi, not testet with gmail, but if you are using the latest release of izPBX 0.9.10 you can config SMTP relay using options:

```
#SMTP SmartHost configuration. Specify DNS name or IP address for the SMTP RelayHost (default: none)
#SMTP_RELAYHOST=
#SMTP_RELAYHOST_USERNAME=
#SMTP_RELAYHOST_PASSWORD=
#SMTP_ALLOWED_SENDER_DOMAINS=
#SMTP_MESSAGE_SIZE_LIMIT=
#SMTP_MAIL_FROM=
```

Kind Regards

**Comment by faspina** [comment]
Ok I set these in the .env file but its doing something weird in the docker log when I try to send a notification from users screen to the users email box 

its use the SMTP Mail From as both the from address and the too address. Even though the too address of the user is completely different 
here is what I have 

SMTP_RELAYHOST=[smtp.gmail.com]:587
SMTP_RELAYHOST_USERNAME=<gmail email>
SMTP_RELAYHOST_PASSWORD=<gmail password>
SMTP_ALLOWED_SENDER_DOMAINS=*
SMTP_MESSAGE_SIZE_LIMIT=
SMTP_MAIL_FROM=<gmail email>

**Comment by ugoviti** [comment]
mmmm.... can you config only:

```
SMTP_RELAYHOST=[smtp.gmail.com]:587
SMTP_RELAYHOST_USERNAME= ---gmail email--
SMTP_RELAYHOST_PASSWORD= --gmail password --
```

and leave commented the others lines?

**Comment by faspina** [comment]
Now it looks like its trying to send it from asterisk@idrivevm  and fails. The too address is correct, it is the address of the user

Oct 07 13:52:52 idrivevm postfix/qmgr[585]: A50FD78DC1: from=<asterisk@idrivevm>, size=15803, nrcpt=1 (queue active)

**Comment by ugoviti** [comment]
Solved?

have you tryed to config:

**Comment by skakdollar** [comment]
Hi, I am trying the following on 20.16.16, as you suggest, but the emails do not go through.

SMTP_MAIL_FROM=my_email@gmail.com
SMTP_MAIL_TO=my_another_email@gmail.com
SMTP_RELAYHOST=smtp.gmail.com:465
SMTP_RELAYHOST_USERNAME=my_email@gmail.com
SMTP_RELAYHOST_PASSWORD=cieeolxtejrpqlpn

I also tried port 587. Tested my_email@gmail.com in another script - it works.
