### ISSUE TITLE
domain doesn't exist outside github

### ISSUE THREAD

**Issue by n8cn** [ugoviti/izdock-izpbx#7]
Following How To Use recipe at: https://hub.docker.com/r/izdock/izpbx-asterisk

-> ... or download latest release from: https://git.initzero.it/initzero/izdock-izpbx/releases and unpack it into a directory (ex. /opt/izpbx):
///
git.initzero.it’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
///

(a git clone of https://github.com/ugoviti/izdock-izpbx.git seemed to work fine.)

**Comment by ugoviti** [comment]
Fixed in the latest commit. Thank you for the advice

Kind regards
